server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:postgresql://order-db:5432/order_db
    username: postgres
    password: root
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      order-history: topic_order_history

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true